package com.dp.trains.model.dto;

public enum UnitPriceDataIntegrity {

    MISSING_FINANCIAL_DATA,
    MISSING_TRAFFIC_DATA,
    MISSING_UNIT_PRICE_DATA,
    MISSING_MARKUP_COEFFICIENTS_DATA,
    ALL_DATA_MISSING,
    ALL_DATA_PRESENT
}