package com.dp.trains.common;

public enum ServiceEnum {

    FINANCIAL_DATA_SERVICE,
    LINE_NUMBER_SERVICE,
    LINE_TYPE_SERVICE,
    RAIL_STATION_SERVICE,
    SECTIONS_SERVICE,
    SERVICE_SERVICE,
    STRATEGIC_COEFFICIENTS_SERVICE,
    TAX_FOR_SERVICES_PER_TRAIN,
    TRAFFIC_DATA_SERVICE,
    TRAINS_USER_DETAIL_SERVICE,
    TRAIN_TYPE_SERVICE,
    UNIT_PRICE_SERVICE,
    CARRIER_COMPANY_SERVICE,
    MARKUP_COEFFICIENT_SERVICE
}